const mongoose = require('mongoose')

const userSchema = new mongoose.Schema({
    username:{
        type:String
    },
    email:{
        type:String
    },
    bio:String,
    joinedClubs:{
        type:mongoose.Schema.Types.Array
    },
    avatar:{
        type:String
    },
    banner:{
        type:String
    },
    joinedTournaments:{
        type:mongoose.Schema.Types.Array
    },
    uid:{
        type:String
    },
    tags:[
        {
            name:String,
            tag:String
        }
    ],
    gamesIPlay:{
        type:[]
    },
    team:{
        type:[]
    },
    balance:{
        type:Number
    },
    followers:[
        {
            username:String,
            email:String,
        }
    ],
    followCount:Number,
    followingCount:Number,
    following:[
        {
            username:String,
            email:String,
        }
    ],
    post:[
        {
            type:String,
            url:String
        }
    ],
    directMessage:[
        {
            name:String,
            avatar:String,
            messages:[
                {
                    date:String,
                    msg:String,
                    type:String
                }
            ]
        }
    ],
    notifications:[
        {
            date:String,
            message:String,
            callToActionLink:String
        }
    ],
    coins:Number,
    diamonds:Number,
    name:String,
    isVerified:Boolean, 
    subscription:[
        {
            name:String,
            duration:String
        }
    ],
    phone:"",
    ip_address:"",
    state:"",
    likedPost:[
        {
            username:String,
            email:String,
        }  
    ]
})

module.exports = userSchema
